fm_version=v1.1.0
fm_git_url=github.com/P2GR/friendsmap-plugin
fm_mainclass=com.friendsmap.FriendsMapPlugin
fm_mainclass_full=com.friendsmap.FriendsMapPluginTest
fm_name="Friends Map"
fm_description="Shows friends, clan members and friends-chat members on the world map."
fm_archivesBaseName=friendsmap-plugin
